### ISSUE TITLE
Consider a grace period for private development

### ISSUE THREAD

**Issue by kemitchell** [kemitchell/shared-component-license#15]
Should the license build in a grace period for development of code covered by copyleft, so that developers can work in private leading up to contribution?

Note that the general automatic-cure terms of Excuse don't cover knowing violation of the rules.

Thanks to @jberkus for this one!

**Comment by adamhjk** [comment]
How is this different than being triggered on public exposure? 

If you build software internally, covered by this license, but expose it to nobody but yourself, do you trigger any of the clauses that require sharing?

**Comment by kemitchell** [comment]
@adamhjk, like Plan 9, RPL, and Open Watcom, as well as the network-copyleft provisions of AGPL and OSL, this licenses's copyleft requirement does _not_ depend on "distribution" or "conveying" or otherwise giving someone else a copy.

If I applied this license to MongoDB, and you patched MongoDB to add a new operator to its API, the license would require to contribute that patch, whether you send a copy of it to anyone else or not.

**Comment by adamhjk** [comment]
Got it.

**Comment by jberkus** [comment]
Yah, and the reason I bring this up is that it's a pretty substantial brake on doing any development with the licensed software at all.  Everyone does experimental development they're not ready to share with the world.

**Comment by kemitchell** [comment]
@jberkus The trade-off here is more or less the same as for Parity. Building in an exception for private changes, even a limited one, becomes its own kind of loophole and complicates the license.

The current draft has a built-in forgiveness provision for unknowing rule-breaking. But that won't apply to devs who know they should release their changes, and choose to delay doing so.

We could write in an _n_-day limited exception to the contribution requirement. Or an exception for changes and additions that turn out to be nonfunctional or useless.

**Comment by jberkus** [comment]
Yeah, that's why I asked about whether the discussion about grace periods on the CPL yielded anything.

**Comment by kemitchell** [comment]
@jberkus I have to admit that I haven't been following CPL discussion. SSPL was priority one at the time, and CPL seemed to me to be posing less interesting issues.

**Comment by bhilburn** [comment]
I also think the forced public development that results from this approach is problematic, and as a project maintainer, I would be concerned that it would inhibit adoption and experimentation.

I don't have an immediate suggestion for a better way to do this, though, and I agree that an `n-day exception` is not a good approach. I'll have to spin on this a bit and see if I can think of other suggestions.

**Comment by kemitchell** [comment]
## First Approach

Must contribute private changes within _n_ days, but only if you continue to use or share the private changes made.

## Second Approach

We could start sketching out some scenarios where someone develops private work, and we don't want to force them to contribute, or contribute immediately.

**Comment by kemitchell** [comment]
Gents, have a look at #22.

**Comment by bradrydzewski** [comment]
> Should the license build in a grace period for development of code covered by copyleft, so that developers can work in private leading up to contribution?

I like how the Business Source License wavies restrictions for non-production use, which would likely include local development and testing in a staging environment.

> The Licensor hereby grants you the right to copy, modify, create derivative works, redistribute, and make non-production use of the Licensed Work.

**Comment by kemitchell** [comment]
@bradrydzewski That's certainly one way to address the issue. But I don't think BSL's nonproduction license is particularly clear or complete.

If we went that route, I think we'd just end up thinking about how to define "non-production".

**Comment by kemitchell** [comment]
I am going to go ahead and close this one, because current master, 8f103662110802982ae814e5d6b7d43df69354c9, includes:

> ## Prototypes
> 
> You need not contribute prototype changes, extensions, or applications that you do not end up using for more than fourteen calendar days, sharing with anyone else, or using to provide service to anyone else.

That's the language that closed #22.

If folks have thoughts on the new language, please do create PRs or issues!
