### ISSUE TITLE
Stop assuming a single developer

### ISSUE THREAD

**Issue by jberkus** [kemitchell/shared-component-license#20]
The license text, as is, currently assumes a single developer with a single homepage.  

Any successful OSS project, particularly one for libraries or reusable components, will accumulate multiple, unrelated contributors over time.  This license should avoid the confusing awkwardness that comes with older licenses by acknowledging that out of the gate: "Developers" and "Homepages".

**Comment by kemitchell** [comment]
@jberkus This license text assumes a single licensor, but doesn't preclude follow-on contributors from appending their own license notices for their own work.

Moreover, terms for follow-on contributions may or may not be under the same terms. The license draft currently permits that, but also allows licensing on more permissive terms.

We disagree on whether success inevitably means contributors from outside the same corporate licensor. But I don't think we have to agree on that point to make the license compatible will all contribution scenarios.

**Comment by kemitchell** [comment]
@jberkus I'm going to close this for now, but also follow up with you privately.
